import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/lib/AntdRegistry';


// 'use client';
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
export const RootLayout = ({ children }: React.PropsWithChildren) => (

  // return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* <Analytics mode={'production'} />; */}
        <Analytics />;
      </body>
    </html>
  );
// }
